apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  progressDeadlineSeconds: 1800
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: akstesth.azurecr.io/flaskapp:latest
        volumeMounts:
        - name: env-config
          mountPath: "/app/.env"
          subPath: ".env"
          readOnly: true
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_ENV
          value: "production"
      volumes:
      - name: env-config
        secret:
          secretName: app-env-file
          items:
          - key: .env
            path: .env

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: flask-app